#!/usr/bin/evn python
from optparse import OptionParser
from rosmanager import cmd


__author__ = 'Hardy.zheng'


parser = OptionParser()
parser.add_option("-c", "--config-file", dest="filename",
                  help="routeros_manager configure file",
                  metavar="FILE")

parser.add_option("-l", "--log-file", dest="logfile",
                  default='/var/log/rosmanager/routeros_manager.log',
                  help="routeros manager log output file",
                  metavar="FILE")

parser.add_option("-w", "--watch-log-file", dest="watchlog",
                  default=False,
                  help="Uses logging handler designed to watch file")

parser.add_option("-d", "--debug", dest="debug",
                  default=False,
                  help="DEBUG instead of default INFO level")


if __name__ == '__main__':
    (options, args) = parser.parse_args()
    if not options.filename:
        parser.error("please input config filename, \
                     eg: --config-file=filename --log-file=filename")
    argv = []
    config_file = '--config-file=%s' % options.filename
    log_file = '--log-file=%s' % options.logfile
    watchlog = '--watch-log-file'
    debug = '--debug'
    argv.append(config_file)
    argv.append(log_file)
    if options.watchlog:
        argv.append(watchlog)
    if options.debug:
        argv.append(debug)
    print argv
    try:
        import sys
        sys.exit(cmd.main(argv))
    except IndexError:
        parser.error('usage: %s --config-file=filename' % sys.argv[0])
